### ISSUE TITLE
extract_gfc() function takes a long time (large area)

### ISSUE THREAD

**Issue by ashjolly** [azvoleff/gfcanalysis#10]
Hi there! Thanks for making this excellent package - it makes accessing this fabulous data resource simple and straightforward!

One question/comment - the extract_gfc() function takes quite a long time if the area of interest is large; for example, I'm doing analysis on the scale of all of British Columbia, Canada. I realize that I'm asking the function to extract and mosaic a lot of spatial data together, so it's not surprising that this takes a long time (and is prone to making my R session crash). However, I thought I'd bring this up in case you had recommendations for how large a spatial extent/max number of tiles that you should apply this function to (and whether it is computationally better to do large areas in pieces)?

Thanks again for making this available - great work!

**Comment by mcooper** [comment]
Hi @ashjolly, sorry for the delayed response on this.

We really cant make specific recommendations as it likely depends a lot on the amount of memory your machine has, how long you are willing to wait, etc.

We are hoping to implement parallelization soon but unfortunately that wont be applicable to the `extract_gfc()` function specifically.

One suggestion would be to check out Google Earth Engine.  Its a totally different software, but it is very efficient for working at large scales, like across all of BC, and it definitely has the Hansen forest cover dataset.
