### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [azvoleff/gfcanalysis#14]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by rsbivand** [comment]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023. 

With strong dependencies on 'rgdal', 'rgeos' and `pkgapi` use of functions: rgeos::gCentroid rgeos::gConvexHull rgeos::gIntersects rgeos::gTouches, you need to take action best by June, latest October 2023. Since you depend on `raster`, you can use `terra` in place of `rgeos` and `rgdal`, as discussed in links in  https://r-spatial.org/r/2023/04/10/evolution3.html. If you use `raster`, you get `terra` anyway, so doing it explicitly is reasonable.

**Comment by rsbivand** [comment]
@azvoleff @mcooper  See also https://r-spatial.org/r/2023/05/15/evolution4.html. Please take urgent steps to resolve this issue. No positive changes appear in the repository. Less than three months remain to retain this package on CRAN.

**Comment by mcooper** [comment]
rgeos and rgdal have now been removed

**Comment by rsbivand** [comment]
Looks OK here, my check log: 
[00check.log](https://github.com/azvoleff/gfcanalysis/files/12061814/00check.log)

**Comment by rsbivand** [comment]
@azvoleff @mcooper Please release 1.8.0 ASAP. Only three weeks left before retiring packages are archived.

**Comment by rsbivand** [comment]
@azvoleff @mcooper R spatial infrastructure packages maptools, rgdal and rgeos will be archived by CRAN on Monday, October 16, 2023. Your package does not pass CMD check when these packages are not available. Expect your package to be archived by CRAN October 17-18 as CRAN checks feed through and your package fails, if not updated by Monday, October 16, 2023. 

No grace period is anticipated, as you have had sufficient time to update your package to remove dependencies on maptools, rgdal and/or rgeos. It remains the case that many packages importing the raster package needlessly depend on retiring packages, as raster stopped using them a year ago.

**Comment by azvoleff** [comment]
Thanks @rsbivand. 1.8.0 was submitted - apologies for the delay
