### ISSUE TITLE
check the overlap between the tiles and the aoi (suggestion)

### ISSUE THREAD

**Issue by pecard** [azvoleff/gfcanalysis#6]
A small detail.

Considering that there is no warning about the CRS to be used when providing an AOI, I think that check the overlap between the tiles and the aoi could be an option of calc_gfc_tiles().

I fact the calc_gfc_tiles() function takes the .shp and internally transform the crs to match the tiles and verify the overlap. The crs of aoi shapefile itself ramains unchanged and plot it against tiles, as suggested, is no useful without another crs transformation.

**Comment by mcooper** [comment]
See commit 63284d796e8bf4a949d00dd4c9c39368353f2cbd
