### ISSUE TITLE
extract_gfc . . . Extents do not overlap

### ISSUE THREAD

**Issue by GatesDupont** [azvoleff/gfcanalysis#8]
I'm trying to run a pretty straightforward implementation of this package, but have run into a problem trying to mosaic multiple tiles in `extract_gfc()`. I can successfully download the files, but once I get to that command, it immediately throws the error below. Any help with this would be much appreciated.

```
library(dplyr)
library(gfcanalysis)
library(raster)
library(rgdal)
library(rnaturalearth)


# making a function for coordinates() w/in a pipe
coordinates_iP = function(spdf){
  coordinates(spdf) = ~long+lat
  return(spdf)
}

# creating extent
df = expand.grid(data.frame(lat = c(3, 10), long = c(-125,-75)))
spdf = coordinates_iP(df)

# getting study area polygon
master = ne_countries(type = 'countries', scale = 'small') %>%
  crop(spdf) %>%
  aggregate() %>%
  as('SpatialPolygonsDataFrame')

# get tile names
tiles = calc_gfc_tiles(master)

# download tiles
download_tiles(tiles, "~/Desktop/tiles")

# moasic and save tiles
gfc_data <- extract_gfc(master, "~/Desktop/tiles", filename='gfc_extract.tif')
```
And the error...
```
Error in .local(x, y, ...) : extents do not overlap
```

**Comment by mcooper** [comment]
This looks like it is an issue with your aoi being right on the boundary of the tiles.  We'll deal with this in a future release, but for now, setting your extent using:

    df = expand.grid(data.frame(lat = c(3, 9.9999), long = c(-125,-75)))
    spdf = coordinates_iP(df)

Should fix it.
