### ISSUE TITLE
Including 2018 data

### ISSUE THREAD

**Issue by smkraus** [azvoleff/gfcanalysis#9]
Hi there,

Thank you so much for providing this package, which has saved us tons of time already. With the 2018 data now out, we were wondering if there's an easy way to include it. Very happy to do this in a pull request as well, if you can give some hints on which parts of the code would have to be changed.

Thanks a lot!

**Comment by mcooper** [comment]
Thanks for bringing this to our attention.  I just pushed a new version of the package to github that should handle 2018.  You can install it for now using `devtools::install_github('azvoleff/gfcanalysis')`, and hopefully we will submit an updated version of the package to CRAN in the coming weeks.

**Comment by smkraus** [comment]
Thanks, that will help us a lot.

**Comment by jacquelineliu24** [comment]
Hi, I'm working on this project as well and managed to install the latest version of the package - thanks so much for helping us with this so quickly! However, I encountered this error message: "Error in .copyWithProperties(x) : no slot of name "legend" for this object of class "RasterStack"" when attempting to use the extract_gfc command. Would you know how we could address this error? Thank you!

**Comment by mcooper** [comment]
Hi @jacquelineliu24, could you give me a copy of the data you were working with when you got this error so I can reproduce it?

**Comment by mcooper** [comment]
This error isn't reproducing for me with R 3.6.1.  I would suggest restarting R and re-running things?  

If you still get the error, try running `rlang::trace_back()`.  That should help you figure out where the error is coming from, and whether it is an issue with `gfcanalysis` or not.

**Comment by jacquelineliu24** [comment]
I've restarted R and it works now. Thanks a lot for checking on this though!

**Comment by davidlvargas** [comment]
Hello all, 

First all, cheers Matt gfcanalysis is a fantastic package!

In other matters, I've been having problems with 2018 data; particularly when I use gfc_stats I don't get the results for 2018.  I'm not sure if it is a generalised thing or just me. 

Thank you in advance!
